extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'next/core-web-vitals'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
rules:
  '@next/next/no-img-element': off
  eqeqeq:
    - error
    - always
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - warn
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
  no-console: warn
